import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";

// Map UI display names → DB enum values (farm_user_role)
const ROLE_TO_DB: Record<string, string> = {
  Admin: "admin",
  Manager: "manager",
  Veterinarian: "vet",
  "Accounts Officer": "accounts",
  Worker: "worker",
};

// Map DB enum values → UI display names
const DB_TO_ROLE: Record<string, string> = {
  admin: "Admin",
  manager: "Manager",
  vet: "Veterinarian",
  accounts: "Accounts Officer",
  worker: "Worker",
};

export async function POST(request: NextRequest) {
  try {
    const { farmNumber, role, username, password } = await request.json();

    if (!farmNumber || !role || !username || !password) {
      return NextResponse.json(
        { error: "All fields are required" },
        { status: 400 }
      );
    }

    const dbRole = ROLE_TO_DB[role];
    if (!dbRole) {
      return NextResponse.json({ error: "Invalid role" }, { status: 400 });
    }

    const admin = createAdminClient();

    // Call the authenticate_farm_user DB function (SECURITY DEFINER, pgcrypto password check)
    const { data: authRows, error: authError } = await admin.rpc(
      "authenticate_farm_user",
      {
        p_farm_number: Number(farmNumber),
        p_role: dbRole,
        p_username: username,
        p_password: password,
      }
    );

    if (authError || !authRows || authRows.length === 0) {
      return NextResponse.json(
        { error: "Invalid Farm ID, role, username, or password" },
        { status: 401 }
      );
    }

    const authUser = authRows[0] as {
      user_id: string;
      farm_id: string;
      station_id: string | null;
      full_name: string;
      role: string;
    };

    // Fetch farm name + number
    const { data: farm, error: farmError } = await admin
      .from("farms")
      .select("farm_name, farm_number")
      .eq("id", authUser.farm_id)
      .single();

    if (farmError || !farm) {
      return NextResponse.json(
        { error: "Farm lookup failed" },
        { status: 500 }
      );
    }

    // Fetch station details if user is assigned to one
    let stationDetails: { id: string; tag: string; name: string; city: string } | null = null;
    if (authUser.station_id) {
      const { data: station } = await admin
        .from("stations")
        .select("id, station_tag, station_name, city")
        .eq("id", authUser.station_id)
        .single();
      if (station) {
        stationDetails = {
          id: station.id,
          tag: station.station_tag,
          name: station.station_name,
          city: station.city,
        };
      }
    }

    // Create a session row — session_token is auto-generated by DB DEFAULT
    const { data: session, error: sessionError } = await admin
      .from("farm_user_sessions")
      .insert({
        farm_user_id: authUser.user_id,
        farm_id: authUser.farm_id,
        station_id: authUser.station_id,
        role: dbRole,
      })
      .select("session_token")
      .single();

    if (sessionError || !session) {
      return NextResponse.json(
        { error: "Could not create session" },
        { status: 500 }
      );
    }

    return NextResponse.json({
      userId: authUser.user_id,
      farmId: authUser.farm_id,
      farmNumber: farm.farm_number,
      farmName: farm.farm_name,
      stationId: authUser.station_id,
      station: stationDetails,
      fullName: authUser.full_name,
      role: DB_TO_ROLE[authUser.role] ?? role,
      sessionToken: session.session_token,
    });
  } catch {
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
